require("plugins")
require("mappings")
require("plugins/onedark")
require("settings")
require("autocommands")
require("dirvish")
require("functions")

require("coc")

require("plugins/neerd_tree")
require("plugins/fzf")
require("plugins/easy_motion")
require("plugins/phpactor")
require("plugins/lualine")
require("plugins/signify")
require("plugins/vim_go")
require("plugins/spelunker")
require("plugins/telescope")
require("plugins/treesitter")
require("plugins/gopls")
require("plugins/ale")
require("plugins/tabline")
require("plugins/indent_line")
