runtime plug-settings/airline.vim
runtime plug-settings/coc.vim
runtime plug-settings/easy_align.vim
runtime plug-settings/easy_motion.vim
runtime plug-settings/fzf.vim
runtime plug-settings/gitgutter.vim
runtime plug-settings/neerd_tree.vim
runtime plug-settings/undotree.vim
runtime plug-settings/text_yank_post.vim
runtime plug-settings/onedar.vim
